- name: Ping Targets
  ping:

- name: Install required dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - python3
    - python3-setuptools
    - python3-dev
    - build-essential
    - python3-pip
    - python3-mysqldb

- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
