---
# tasks file for mysql_db
- name: Install MySQL database
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - mysql-server
    - mysql-client

- name: Start MySQL
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create Application DB
  mysql_db:
    name: "{{ db_name }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: Create a DB User
  mysql_user:
    name: "{{ db_user }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    password: "{{ db_password }}"
    priv: "*.*:ALL"
    state: present
